spring.application.name=012_springbootjpa

#Set Port Number
server.port=8081

#MYSQL Configuration
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/fsad
spring.datasource.username=root
spring.datasource.password=Pwd@1292

#JPA Configuration
spring.jpa.hibernate.ddl-auto=update
